name: Java CI

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'
      - name: Build with Maven
        run: echo "Build maven with java version ${{ inputs.java_version }}"

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: github/codeql-action/init@v2
      - uses: github/codeql-action/analyze@v2