# Reusable workflow
name: Java build workflow

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout workflow-template repo
        uses: actions/checkout@v4
        with:
          repository: nminhquang/test123
          path: workflow-template

      - name: Read Variable File
        id: read-vars
        run: |
          ls -la workflow-template/variables
          pwd
          source workflow-template/variables/$(basename $GITHUB_REPOSITORY).env
          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Build Maven
        run: |
          echo "Build maven ${{ env.JAVA_VERSION }}"
