
name: React build workflow

on:
  workflow_call:
    inputs:
      react_version:
        required: true
        type: string
      node_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install Specific React Version
        run: npm install react@$${{ inputs.react_version }}react-dom@${{ inputs.react_version }}

      - name: Build React
        run: |
          echo "Build React ${{ inputs.react_version }} with node ${{ inputs.react_version }}"